### ISSUE TITLE
Attributes annotations don't work with cucumber-java8 syntax

### ISSUE THREAD

**Issue by endless-qa** [reportportal/agent-java-cucumber6#26]
**Client:** 5.5.0
**Agent:** 5.0.2 (agent-java-cucumber6)

**Description:**
We use cucumber-java8 syntax in defining steps. Hence, the only way to placed the Report Portal's `@Attributes` annotation was like this:

`@Attributes(multiValueAttributes = { @MultiValueAttribute(key = "myKey", values = { "valueOne", "valueTwo" }) })
Given("^user logs in", this::logInPlease);`

I was expecting the assigned attributes to appear on Report Portal but they didn't. I tried to place the `@Attributes` annotation on the `logInPlease()` method that is called in the step but that didn't change anything.

I tried both, ScenarioReporter and StepReporter. Am I missing something of cucumber-java8 syntax is not supported by this agent?

**Comment by HardNorth** [comment]
`cucumber-java8` Given, When, Then steps are static methods, their calls are inlined in code. And it's not possible in java to get annotations from method calls. Also Cucumber does not provide methods from which these steps are called. And it's also conceptual question how to handle multiple steps defined in one method/constructor. So no, it's not a bug or issue. Right now we don't have any plans to support such functionality.

Apart from that `cucumber-java8` is a subject to [deprecation](https://github.com/cucumber/cucumber-jvm/issues/2174).
