### ISSUE TITLE
Dynamic Attributes/Parameters and Description update at test and suite level for cucumber

### ISSUE THREAD

**Issue by qaautomationreqts** [reportportal/agent-java-cucumber6#32]
Dynamic Attributes/Parameters and Description update at test and suite level for cucumber
I am looking to alter (Add/Update) attributes for the executing scenario in the ReportPortal. i.e. add an attribute to the current test step. Also, Looking to alter attributes and description at suite level.
Attributes and their value will be dynamic based on execution.

Please suggest if we have any mechanism to achieve this need.

**Comment by qaautomationreqts** [comment]
@HardNorth - Please share your inputs on this

**Comment by HardNorth** [comment]
@qaautomationreqts I can hardly imagine any example of such implementation or usage, especially given the fact that test and suite levels are established on Gherkin level in Feature files. Could you please describe in details how you see it?

**Comment by HardNorth** [comment]
Abandoned.
