### ISSUE TITLE
Make @Attributes annotation available on Scenarion/Scenario Outline level

### ISSUE THREAD

**Issue by Gribochechek** [reportportal/agent-java-cucumber6#39]
**Is your feature request related to a problem? Please describe.**
As For now @Attributes annotation is available for Steps. But custom attributes can not be set for the whole Scenario. 

**Describe the solution you'd like**
It would be nice to have ability to pass custom attributes per each Scenario. It will give opportunity to create Component Health diagram view, based on features and Scenarios

**Comment by HardNorth** [comment]
@Gribochechek I can hardly imagine any example of such implementation, could you please describe in details how you see it?

**Comment by HardNorth** [comment]
Abandoned

**Comment by iRetlaWM** [comment]
this could be usefull for component health https://reportportal.io/docs/dashboards-and-widgets/ComponentHealthCheck/
