### ISSUE TITLE
Attribute Annotation at Steps in "Step definition" code in cucumber framework doesn't work

### ISSUE THREAD

**Issue by Shivin89** [reportportal/agent-java-cucumber6#9]
**Describe the bug**
Given:- I need to add attributes at steps in my step definition file (Step definition in Given, Then format ) like cucumber.
When:- I add attributes Annotation provided by Report Portal like below 
         @Attributes(attributes = { @Attribute(key = "Key", value = "Value") })
	My Step Starts ---@Given("user is on login page")
Then:- Attributes are not added to my steps in the Report Portal.

Util class method   (Method retrieveMethod (Field definitionMatchField, TestStep testStep))
 is not returning the step definition, which is why the  getAttributes(@Nonnull TestStep testStep) return null.

---rq.setAttributes(getAttributes(testStep));

My repo: https://stash.cdk.com/projects/PEOEQA/repos/engqa.ui.junit.cucumber/browse
Example Repo provided by Report Portal:https://github.com/reportportal/agent-java-cucumber6

**Expected behavior**
Given I need to add attributes at steps in my step definition file (Step definition in Given, Then format ) like cucumber.
When I add attributes Annotation provided by Report Portal like below 
         @Attributes(attributes = { @Attribute(key = "Key", value = "Value") })
	My Step Starts ---@Given("user is on login page")
Then Attributes are added to my steps in the Report Portal.

**Screenshots**

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is] 
 - Current version:API Service: 5.3.3;Index Service: 5.0.10;Authorization Service: 5.3.3;Service UI: 5.3.3;

**Comment by HardNorth** [comment]
@Shivin89 I cannot confirm this. We have a separate integration test on this, it would failed if the feature was broken: 
* Feature: https://github.com/reportportal/agent-java-cucumber6/blob/develop/src/test/resources/features/belly.feature
* Stepdefs: https://github.com/reportportal/agent-java-cucumber6/blob/develop/src/test/java/com/epam/reportportal/cucumber/integration/feature/BellyStepdefs.java

You can run it with this runner:
```java
import io.cucumber.testng.AbstractTestNGCucumberTests;
import io.cucumber.testng.CucumberOptions;

@CucumberOptions(features = "src/test/resources/features/belly.feature", glue = {
		"com.epam.reportportal.cucumber.integration.feature" }, plugin = { "pretty", "com.epam.reportportal.cucumber.StepReporter" })
public class TestRunner extends AbstractTestNGCucumberTests {

}
```

The result:
![Screen Shot 2021-02-08 at 1 05 33 PM](https://user-images.githubusercontent.com/4364466/107204951-5a2e4400-6a0e-11eb-96f6-4b4619a77ca5.png)
---

There are only two options which come in my mind:
1. Newer versions of Cucumber 6 have different class structure.
2. Newer versions of Java do not allow these reflection calls in `retrieveMethod`.

@Shivin89 Can you please post Cucumber and Java versions you use?

**Comment by HardNorth** [comment]
Fixed in: https://github.com/reportportal/agent-java-cucumber6/releases/tag/5.0.2

**Comment by Shivin89** [comment]
Is this fixed?

**Comment by HardNorth** [comment]
@Shivin89 Yes
